# Generated by Django 4.0.3 on 2022-06-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='computernadscreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_id', models.CharField(default=0, max_length=255)),
                ('PC_Barcode', models.CharField(default=0, max_length=255)),
                ('Bldg', models.CharField(default=0, max_length=255)),
                ('Floor', models.CharField(default=0, max_length=255)),
                ('Department', models.CharField(default=0, max_length=255)),
                ('Socket', models.CharField(default=0, max_length=255)),
                ('room', models.CharField(default=0, max_length=255)),
                ('PC_SN', models.CharField(default=0, max_length=255)),
                ('PC_Name', models.CharField(default=0, max_length=255)),
                ('pc_Make', models.CharField(default=0, max_length=255)),
                ('pc_Model', models.CharField(default=0, max_length=255)),
                ('pc_CPU', models.CharField(default=0, max_length=255)),
                ('pc_RAM', models.CharField(default=0, max_length=255)),
                ('pc_Username', models.CharField(default=0, max_length=255)),
                ('pc_Warranty', models.CharField(default=0, max_length=255)),
                ('pc_PO', models.CharField(default=0, max_length=255)),
                ('screen_Barcode', models.CharField(default=0, max_length=255)),
                ('screen_SN', models.CharField(default=0, max_length=255)),
                ('screen_Make', models.CharField(default=0, max_length=255)),
                ('screen_Model', models.CharField(default=0, max_length=255)),
                ('screen_PO', models.CharField(default=0, max_length=255)),
                ('scrren_size', models.CharField(default=0, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_id', models.CharField(default=0, max_length=255)),
                ('Barcode', models.CharField(default=0, max_length=255)),
                ('Bldg', models.CharField(default=0, max_length=255)),
                ('Floor', models.CharField(default=0, max_length=255)),
                ('Department', models.CharField(default=0, max_length=255)),
                ('Socket', models.CharField(default=0, max_length=255)),
                ('room', models.CharField(default=0, max_length=255)),
                ('SN', models.CharField(default=0, max_length=255)),
                ('ipaddress', models.CharField(default=0, max_length=255)),
                ('Make', models.CharField(default=0, max_length=255)),
                ('Model', models.CharField(default=0, max_length=255)),
                ('Warranty', models.CharField(default=0, max_length=255)),
                ('PO', models.CharField(default=0, max_length=255)),
            ],
        ),
    ]
