# Generated by Django 4.0.3 on 2022-06-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computernadscreen',
            old_name='PC_Barcode',
            new_name='Barcode',
        ),
        migrations.RenameField(
            model_name='computernadscreen',
            old_name='pc_id',
            new_name='ids',
        ),
        migrations.RenameField(
            model_name='printer',
            old_name='printer_id',
            new_name='ids',
        ),
    ]
