# Generated by Django 4.0.3 on 2022-06-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_ipaddress_printer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computernadscreen',
            name='ids',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='ids',
        ),
    ]
