import ipaddress
from django.db import models

class computernadscreen(models.Model):
    Barcode = models.CharField(max_length=255,default=0)
    Bldg = models.CharField(max_length=255,default=0)
    Floor = models.CharField(max_length=255,default=0)
    Department = models.CharField(max_length=255,default=0)
    Socket = models.CharField(max_length=255,default=0)
    room = models.CharField(max_length=255,default=0)
    PC_SN = models.CharField(max_length=255,default=0)
    PC_Name = models.CharField(max_length=255,default=0)
    pc_Make = models.CharField(max_length=255,default=0)
    pc_Model = models.CharField(max_length=255,default=0)
    pc_CPU = models.CharField(max_length=255,default=0)
    pc_RAM = models.CharField(max_length=255,default=0)
    pc_Username = models.CharField(max_length=255,default=0)
    pc_Warranty = models.CharField(max_length=255,default=0)
    pc_PO = models.CharField(max_length=255,default=0)
    screen_Barcode = models.CharField(max_length=255,default=0)
    screen_SN = models.CharField(max_length=255,default=0)
    screen_Make = models.CharField(max_length=255,default=0)
    screen_Model = models.CharField(max_length=255,default=0)
    screen_PO = models.CharField(max_length=255,default=0)
    scrren_size = models.CharField(max_length=255,default=0)

class printer(models.Model):
    Barcode = models.CharField(max_length=255,default=0)
    Bldg = models.CharField(max_length=255,default=0)
    Floor = models.CharField(max_length=255,default=0)
    Department = models.CharField(max_length=255,default=0)
    Socket = models.CharField(max_length=255,default=0)
    room = models.CharField(max_length=255,default=0)
    SN = models.CharField(max_length=255,default=0)
    address = models.CharField(max_length=255,default=0)
    Make = models.CharField(max_length=255,default=0)
    Model = models.CharField(max_length=255,default=0)
    Warranty = models.CharField(max_length=255,default=0)
    PO = models.CharField(max_length=255,default=0)
