# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.user_info import UserInfo
import re
from openapi_server import util

from openapi_server.models.user_info import UserInfo  # noqa: E501
import re  # noqa: E501

class AllUserInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, email=None, password=None, first_name=None, last_name=None, account_type=None, gender=None, age=None, followers=None, following=None, pending_follow=None, incoming_follow=None):  # noqa: E501
        """AllUserInfo - a model defined in OpenAPI

        :param id: The id of this AllUserInfo.  # noqa: E501
        :type id: str
        :param email: The email of this AllUserInfo.  # noqa: E501
        :type email: str
        :param password: The password of this AllUserInfo.  # noqa: E501
        :type password: str
        :param first_name: The first_name of this AllUserInfo.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this AllUserInfo.  # noqa: E501
        :type last_name: str
        :param account_type: The account_type of this AllUserInfo.  # noqa: E501
        :type account_type: str
        :param gender: The gender of this AllUserInfo.  # noqa: E501
        :type gender: str
        :param age: The age of this AllUserInfo.  # noqa: E501
        :type age: int
        :param followers: The followers of this AllUserInfo.  # noqa: E501
        :type followers: List[UserInfo]
        :param following: The following of this AllUserInfo.  # noqa: E501
        :type following: List[UserInfo]
        :param pending_follow: The pending_follow of this AllUserInfo.  # noqa: E501
        :type pending_follow: List[UserInfo]
        :param incoming_follow: The incoming_follow of this AllUserInfo.  # noqa: E501
        :type incoming_follow: List[UserInfo]
        """
        self.openapi_types = {
            'id': str,
            'email': str,
            'password': str,
            'first_name': str,
            'last_name': str,
            'account_type': str,
            'gender': str,
            'age': int,
            'followers': List[UserInfo],
            'following': List[UserInfo],
            'pending_follow': List[UserInfo],
            'incoming_follow': List[UserInfo]
        }

        self.attribute_map = {
            'id': '_id',
            'email': 'Email',
            'password': 'Password',
            'first_name': 'FirstName',
            'last_name': 'LastName',
            'account_type': 'AccountType',
            'gender': 'Gender',
            'age': 'Age',
            'followers': 'Followers',
            'following': 'Following',
            'pending_follow': 'PendingFollow',
            'incoming_follow': 'IncomingFollow'
        }

        self._id = id
        self._email = email
        self._password = password
        self._first_name = first_name
        self._last_name = last_name
        self._account_type = account_type
        self._gender = gender
        self._age = age
        self._followers = followers
        self._following = following
        self._pending_follow = pending_follow
        self._incoming_follow = incoming_follow

    @classmethod
    def from_dict(cls, dikt) -> 'AllUserInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The all_user_info of this AllUserInfo.  # noqa: E501
        :rtype: AllUserInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this AllUserInfo.


        :return: The id of this AllUserInfo.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AllUserInfo.


        :param id: The id of this AllUserInfo.
        :type id: str
        """
        if id is not None and not re.search(r'^[a-fA-F0-9]{24}$', id):  # noqa: E501
            raise ValueError("Invalid value for `id`, must be a follow pattern or equal to `/^[a-fA-F0-9]{24}$/`")  # noqa: E501

        self._id = id

    @property
    def email(self):
        """Gets the email of this AllUserInfo.

        email must have the following format something@someserver.something  # noqa: E501

        :return: The email of this AllUserInfo.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this AllUserInfo.

        email must have the following format something@someserver.something  # noqa: E501

        :param email: The email of this AllUserInfo.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501
        if email is not None and len(email) > 50:
            raise ValueError("Invalid value for `email`, length must be less than or equal to `50`")  # noqa: E501
        if email is not None and not re.search(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', email):  # noqa: E501
            raise ValueError("Invalid value for `email`, must be a follow pattern or equal to `/\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b/`")  # noqa: E501

        self._email = email

    @property
    def password(self):
        """Gets the password of this AllUserInfo.

        Minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character  # noqa: E501

        :return: The password of this AllUserInfo.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this AllUserInfo.

        Minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character  # noqa: E501

        :param password: The password of this AllUserInfo.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501
        if password is not None and not re.search(r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$', password):  # noqa: E501
            raise ValueError("Invalid value for `password`, must be a follow pattern or equal to `/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/`")  # noqa: E501

        self._password = password

    @property
    def first_name(self):
        """Gets the first_name of this AllUserInfo.

        no special characters or numbers are allowed  # noqa: E501

        :return: The first_name of this AllUserInfo.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this AllUserInfo.

        no special characters or numbers are allowed  # noqa: E501

        :param first_name: The first_name of this AllUserInfo.
        :type first_name: str
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")  # noqa: E501
        if first_name is not None and len(first_name) > 15:
            raise ValueError("Invalid value for `first_name`, length must be less than or equal to `15`")  # noqa: E501
        if first_name is not None and len(first_name) < 3:
            raise ValueError("Invalid value for `first_name`, length must be greater than or equal to `3`")  # noqa: E501
        if first_name is not None and not re.search(r'^[a-zA-Z][a-zA-Z .,\'-]*$', first_name):  # noqa: E501
            raise ValueError("Invalid value for `first_name`, must be a follow pattern or equal to `/^[a-zA-Z][a-zA-Z .,'-]*$/`")  # noqa: E501

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this AllUserInfo.

        no special characters or numbers are allowed  # noqa: E501

        :return: The last_name of this AllUserInfo.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this AllUserInfo.

        no special characters or numbers are allowed  # noqa: E501

        :param last_name: The last_name of this AllUserInfo.
        :type last_name: str
        """
        if last_name is None:
            raise ValueError("Invalid value for `last_name`, must not be `None`")  # noqa: E501
        if last_name is not None and len(last_name) > 15:
            raise ValueError("Invalid value for `last_name`, length must be less than or equal to `15`")  # noqa: E501
        if last_name is not None and len(last_name) < 3:
            raise ValueError("Invalid value for `last_name`, length must be greater than or equal to `3`")  # noqa: E501
        if last_name is not None and not re.search(r'^[a-zA-Z][a-zA-Z .,\'-]*$', last_name):  # noqa: E501
            raise ValueError("Invalid value for `last_name`, must be a follow pattern or equal to `/^[a-zA-Z][a-zA-Z .,'-]*$/`")  # noqa: E501

        self._last_name = last_name

    @property
    def account_type(self):
        """Gets the account_type of this AllUserInfo.

        type of account  # noqa: E501

        :return: The account_type of this AllUserInfo.
        :rtype: str
        """
        return self._account_type

    @account_type.setter
    def account_type(self, account_type):
        """Sets the account_type of this AllUserInfo.

        type of account  # noqa: E501

        :param account_type: The account_type of this AllUserInfo.
        :type account_type: str
        """
        allowed_values = ["private", "public"]  # noqa: E501
        if account_type not in allowed_values:
            raise ValueError(
                "Invalid value for `account_type` ({0}), must be one of {1}"
                .format(account_type, allowed_values)
            )

        self._account_type = account_type

    @property
    def gender(self):
        """Gets the gender of this AllUserInfo.


        :return: The gender of this AllUserInfo.
        :rtype: str
        """
        return self._gender

    @gender.setter
    def gender(self, gender):
        """Sets the gender of this AllUserInfo.


        :param gender: The gender of this AllUserInfo.
        :type gender: str
        """
        allowed_values = ["male", "female"]  # noqa: E501
        if gender not in allowed_values:
            raise ValueError(
                "Invalid value for `gender` ({0}), must be one of {1}"
                .format(gender, allowed_values)
            )

        self._gender = gender

    @property
    def age(self):
        """Gets the age of this AllUserInfo.


        :return: The age of this AllUserInfo.
        :rtype: int
        """
        return self._age

    @age.setter
    def age(self, age):
        """Sets the age of this AllUserInfo.


        :param age: The age of this AllUserInfo.
        :type age: int
        """
        if age is None:
            raise ValueError("Invalid value for `age`, must not be `None`")  # noqa: E501
        if age is not None and age < 18:  # noqa: E501
            raise ValueError("Invalid value for `age`, must be a value greater than or equal to `18`")  # noqa: E501

        self._age = age

    @property
    def followers(self):
        """Gets the followers of this AllUserInfo.

        list of followers  # noqa: E501

        :return: The followers of this AllUserInfo.
        :rtype: List[UserInfo]
        """
        return self._followers

    @followers.setter
    def followers(self, followers):
        """Sets the followers of this AllUserInfo.

        list of followers  # noqa: E501

        :param followers: The followers of this AllUserInfo.
        :type followers: List[UserInfo]
        """

        self._followers = followers

    @property
    def following(self):
        """Gets the following of this AllUserInfo.

        List of people who you followed  # noqa: E501

        :return: The following of this AllUserInfo.
        :rtype: List[UserInfo]
        """
        return self._following

    @following.setter
    def following(self, following):
        """Sets the following of this AllUserInfo.

        List of people who you followed  # noqa: E501

        :param following: The following of this AllUserInfo.
        :type following: List[UserInfo]
        """

        self._following = following

    @property
    def pending_follow(self):
        """Gets the pending_follow of this AllUserInfo.

        list of sent follows request  # noqa: E501

        :return: The pending_follow of this AllUserInfo.
        :rtype: List[UserInfo]
        """
        return self._pending_follow

    @pending_follow.setter
    def pending_follow(self, pending_follow):
        """Sets the pending_follow of this AllUserInfo.

        list of sent follows request  # noqa: E501

        :param pending_follow: The pending_follow of this AllUserInfo.
        :type pending_follow: List[UserInfo]
        """

        self._pending_follow = pending_follow

    @property
    def incoming_follow(self):
        """Gets the incoming_follow of this AllUserInfo.

        list of recieved follows request  # noqa: E501

        :return: The incoming_follow of this AllUserInfo.
        :rtype: List[UserInfo]
        """
        return self._incoming_follow

    @incoming_follow.setter
    def incoming_follow(self, incoming_follow):
        """Sets the incoming_follow of this AllUserInfo.

        list of recieved follows request  # noqa: E501

        :param incoming_follow: The incoming_follow of this AllUserInfo.
        :type incoming_follow: List[UserInfo]
        """

        self._incoming_follow = incoming_follow
